spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/candidate-assessment
  mail:
    host: localhost
    port: 1025
#    username: elcaassessment@gmail.com
#    password: ElcaInformationTechnology
#    properties.mail.smtp.auth: true
#    properties.mail.smtp.starttls.enable: true
keycloak:
  principal-attribute: preferred_username
  public-client: true
  use-resource-role-mappings: true