spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/candidate-assessment
  mail:
    host: localhost
    port: 1025
#    properties.mail.smtp.auth: true
#    properties.mail.smtp.starttls.enable: true
